#!/usr/bin/env python3
"""Build only public static files. No network, no deploy, no app tree access."""
from pathlib import Path
from html import escape
from urllib.parse import urlsplit
import argparse, json, re, shutil
ROOT=Path(__file__).resolve().parent
parser=argparse.ArgumentParser()
parser.add_argument('--release',action='store_true',help='Refuse incomplete public identity/content/approval')
parser.add_argument('--check-ready',action='store_true',help='Validate final content locally without granting publication approval')
args=parser.parse_args()
content=json.loads((ROOT/'content/LegalContent.json').read_text())
config=json.loads((ROOT/'content/LegalConfiguration.json').read_text())
if args.release or args.check_ready:
    needed=['holder','supportEmail','supportProvider','rightsConfirmed']
    if args.release: needed.append('publicationApproved')
    missing=[k for k in needed if not config.get(k)]
    if config.get('status') not in ('readyForPublication','published'): missing.append('status=readyForPublication or published')
    for key in ['privacyURL','supportURL']:
        u=urlsplit(config.get(key) or '')
        if config.get('status')=='published' and (u.scheme!='https' or not u.netloc or u.username or u.password): missing.append(key+' valid HTTPS')
    if not re.fullmatch(r'[^\s@]+@[^\s@]+\.[^\s@]+',config.get('supportEmail') or ''): missing.append('valid support email')
    # "Cambios pendientes" describes offline operations, not unfinished legal copy.
    draft_pattern=r'\b(?:borrador|draft|propuest\w*|proposed|awaiting)\b|\bpendientes?\s+(?:de|del titular)|\bremain(?:s)? to be specified\b|\bstill need to be substantiated\b'
    if re.search(draft_pattern,json.dumps(content,ensure_ascii=False),re.I): missing.append('finalise draft wording')
    if missing: parser.error('Publication remains blocked: '+', '.join(missing))
site=ROOT/'site'
# This directory is generated by this script; it never includes content, scripts or .git.
if site.exists(): shutil.rmtree(site)
site.mkdir(); shutil.copytree(ROOT/'assets',site/'assets'); (site/'.nojekyll').touch()
labels={
 'es':{'skip':'Saltar al contenido','home':'Privacidad y ayuda para tu hogar','intro':'Información sobre tus datos, ayuda con la app y límites de sus estimaciones.','draft':'Borrador local · pendiente de aprobación','notice':'Correo de soporte y acreditación del icono pendientes. Esta versión todavía no debe publicarse ni enviarse a Apple.','language':'English','footer':'Revisión del texto','copyright':'titular pendiente de confirmación','email':'contacto pendiente de confirmación','provider':'pendiente de elegir'},
 'en':{'skip':'Skip to content','home':'Privacy and help for your household','intro':'Information about your data, help with the app and the limits of its estimates.','draft':'Local draft · awaiting approval','notice':'Support email and icon provenance pending. This version must not yet be published or submitted to Apple.','language':'Español','footer':'Text revision','copyright':'owner awaiting confirmation','email':'contact awaiting confirmation','provider':'awaiting selection'}}
keys=['privacy','support','estimates','licenses']; names={'privacy':'privacy.html','support':'support.html','estimates':'estimates.html','licenses':'legal.html'}
def render(text,lang):
    values={'holder':config['holder'] or labels[lang]['copyright'],'email':config['supportEmail'] or labels[lang]['email'],'provider':config['supportProvider'] or labels[lang]['provider'],'retention':config['supportRetentionMonths'],'year':config['copyrightYear']}
    for k,v in values.items(): text=text.replace('{{'+k+'}}',str(v))
    assert '{{' not in text
    return escape(text)
for lang in ['es','en']:
    target=site/lang; target.mkdir(); other='en' if lang=='es' else 'es'; l=labels[lang]; docs=content['languages'][lang]
    notice='' if config['status'] in ('readyForPublication','published') else '<aside class="notice" aria-label="'+l['draft']+'"><strong>'+l['draft']+'</strong><p>'+l['notice']+'</p></aside>'
    for key in ['index']+keys:
        file='index.html' if key=='index' else names[key]
        title='HomeRunway' if key=='index' else docs[key]['title']+' · HomeRunway'
        nav=''.join('<a href="'+names[k]+'"'+(' aria-current="page"' if k==key else '')+'>'+escape(docs[k]['title'])+'</a>' for k in keys)
        nav+='<a href="../'+other+'/'+file+'" lang="'+other+'" hreflang="'+other+'">'+l['language']+'</a>'
        if key=='index':
            body='<h1>'+l['home']+'</h1><p>'+l['intro']+'</p><div class="links">'+''.join('<a href="'+names[k]+'">'+escape(docs[k]['title'])+'</a>' for k in keys)+'</div>'
        else:
            doc=docs[key]; body='<article><h1>'+escape(doc['title'])+'</h1>'+''.join('<section><h2>'+escape(s['title'])+'</h2>'+''.join('<p>'+render(p,lang)+'</p>' for p in s['paragraphs'])+'</section>' for s in doc['sections'])+'</article>'
            if key=='support' and config['supportEmail']:
                body+='<p><a href="mailto:'+escape(config['supportEmail'],quote=True)+'">'+escape(config['supportEmail'])+'</a></p>'
            if key=='privacy':
                body+='<p><a href="https://www.apple.com/legal/privacy/">Apple: '+('privacidad' if lang=='es' else 'privacy')+'</a> · <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub: '+('privacidad' if lang=='es' else 'privacy')+'</a> · <a href="https://policies.google.com/privacy?hl='+lang+'">Google: '+('privacidad' if lang=='es' else 'privacy')+'</a> · <a href="https://policies.google.com/privacy/frameworks?hl='+lang+'">Google: '+('transferencias' if lang=='es' else 'transfers')+'</a> · <a href="https://www.aepd.es/">AEPD</a></p>'
            if key=='licenses': body+='<p><a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">'+('EULA estándar de Apple' if lang=='es' else 'Standard Apple EULA')+'</a></p>'
        html='<!doctype html><html lang="'+lang+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="referrer" content="no-referrer"><meta name="description" content="'+escape(l['intro'],quote=True)+'"><title>'+escape(title)+'</title><link rel="stylesheet" href="../assets/site.css"><link rel="icon" href="../assets/icon.png"></head><body><a class="skip" href="#main">'+l['skip']+'</a><header><a class="brand" href="index.html"><img src="../assets/icon.png" alt="" width="44" height="44">HomeRunway</a><nav aria-label="'+('Información y idioma' if lang=='es' else 'Information and language')+'">'+nav+'</nav></header><main id="main" tabindex="-1">'+notice+body+'</main><footer><p class="meta">'+l['footer']+': '+content['revision']+'</p><p>'+render(content['copyrightNotices'][lang],lang)+'</p><a href="index.html">HomeRunway</a></footer></body></html>'
        (target/file).write_text(html)
(site/'index.html').write_text('<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HomeRunway</title><link rel="stylesheet" href="assets/site.css"></head><body><main><h1>HomeRunway</h1><div class="links"><a href="es/index.html" lang="es">Español</a><a href="en/index.html" lang="en">English</a></div></main></body></html>')
print('Built '+str(site)+' ('+config['status']+'); no network or publication performed.')
